[package]
name = "assignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.22.0"
clap = { version = "3.1.6",features = ["derive"] }
chrono = "0.4"

